import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Techpool X - Webflow Ecommerce website template",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <Head>
      <link rel="icon" href="https://assets-global.website-files.com/61800161ed9edf6bdd5c6c4d/618003a199928cc543e960b4_favicon-applay-x-template.svg" />
    </Head>
    <body className={inter.className}>{children}</body>
  </html>
  );  
}
